### ISSUE TITLE
How do you report the results for Source-only and Target-Supervised model?

### ISSUE THREAD

**Issue by avijit9** [CVIR/CoMix#2]
Hi, 

I would like to know if you have a script to run `source only` and `target supervised` models? From the paper, I see that the values are exactly the same as SAVA, ECCV'20 paper. So, I would like to clarify if you report these values from the SAVA paper or do you have script to reproduce the results?

TIA.

**Comment by AadSah** [comment]
Hi

Yes, we have reported the values from the SAVA paper, but we got similar values when we ran the corresponding experiments at our end.
For source-only: use `--lambda_bgm 0.0 --lambda_tpl 0.0`
For target-supervised: run source-only as mentioned above, and keep `--src_dataset` and `--tgt_dataset` the same.

Thanks
